# Generated by Django 4.1.1 on 2022-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0002_relation_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
