# Generated by Django 4.1.1 on 2022-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0003_tag_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="relation",
        ),
        migrations.RemoveField(
            model_name="link",
            name="relation",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="relation",
        ),
        migrations.AddField(
            model_name="relation",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, to="relations.attachment"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="links",
            field=models.ManyToManyField(blank=True, to="relations.link"),
        ),
        migrations.AddField(
            model_name="relation",
            name="tags",
            field=models.ManyToManyField(blank=True, to="relations.tag"),
        ),
    ]
