version: '3'

volumes:
  sauron_local_postgres_data: {}
  sauron_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sauron_local_django
    container_name: sauron_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sauron_production_postgres
    container_name: sauron_local_postgres
    volumes:
      - sauron_local_postgres_data:/var/lib/postgresql/data:Z
      - sauron_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: sauron_local_docs
    container_name: sauron_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./sauron:/app/sauron:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: sauron_local_mailhog
    ports:
      - "8025:8025"
