[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'

[tool.flake8]
max-line-length = 79
exclude = [".tox", ".git", "*/migrations/*", "*/static/CACHE/*", "docs", "node_modules", "venv"]

[tool.pycodestyle]
max-line-length = 79
exclude = [".tox", ".git", "*/migrations/*", "*/static/CACHE/*", "docs", "node_modules", "venv"]

[tool.isort]
profile = "black"
line_length = 79
lines_after_imports = 2
known_first_party = ["sauron", "config"]
multi_line_output = 3
default_section = "THIRDPARTY"
skip = "venv/"
skip_glob = "**/migrations/*.py"
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.pylint.BASIC]
good-names = [
    "e", # (exception) as e
    "f", # (file) as f
    "k", # for k, v in
    "v", # for k, v in
    "dt", # datetime
]

[tool.pylint.MASTER]
load-plugins = "pylint_django"
django-settings-module = "config.settings.base"
ignore = [
    "tests",
    "migrations"
]
disable = [
    "C0103", # invalid-name
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "C0209", # consider-using-f-string
    "C0415", # import-outside-toplevel
    "W0511", # fixme
    "W0703", # broad-except
    "W0707", # raise-missing-from
    "R0801", # duplicate-code
    "R0901", # too-many-ancestors
    "R0902", # too-many-instance-attributes
    "R0903", # too-few-public-methods
    "R0913", # too-many-arguments
    "E1136", # unsubscriptable-object (false positive with python 3.9)
]

[tool.pylint.FORMAT]
max-line-length = 79

[tool.pylint.DESIGN]
max-parents = 13

[tool.pylint.TYPECHECK]
generated-members = "REQUEST,acl_users,aq_parent,\"[a-zA-Z]+_set{1,2}\",save,delete"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings.test"

[tool.coverage.run]
include = "sauron/*"
omit = ["*migrations*", "*tests*"]
plugins = [
    "django_coverage_plugin",
]
